### ISSUE TITLE
TODO items aka

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#79]
- [x] abuse contact export bot : put into production & test
- [x] subject lines for newstrategy branch
- [x] test with test data
- [x] make cronjob for create_incident_reports and cli

**Comment by aaronkaplan** [comment]
works
